# Generated by Django 5.2.13 on 2026-04-17 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_pedido_estado_alter_pedido_mesa_o_online_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_preparacion', 'En Preparación'), ('listo', 'Listo'), ('pagado', 'Pagado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.pedido'),
        ),
    ]
