# Generated by Django 5.2.13 on 2026-04-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_pedido_estado_alter_transaccion_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_preparacion', 'En Preparación'), ('listo', 'Listo'), ('entregada', 'Entregada'), ('pagado', 'Pagado')], default='pendiente', max_length=20),
        ),
    ]
