# Generated by Django 4.2.28 on 2026-03-17 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingrediente",
            name="stock",
            field=models.PositiveIntegerField(
                default=0, help_text="Cantidad disponible en inventario"
            ),
        ),
        migrations.CreateModel(
            name="ProductoIngrediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Cantidad de ingrediente necesaria por unidad de producto",
                    ),
                ),
                (
                    "ingrediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.ingrediente",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.producto",
                    ),
                ),
            ],
            options={"unique_together": {("producto", "ingrediente")},},
        ),
    ]
