# Generated by Django 5.2.13 on 2026-04-15 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_ingrediente_stock_productoingrediente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('descuento', 'Descuento por pedido'), ('ajuste', 'Ajuste manual')], max_length=20)),
                ('cantidad', models.IntegerField(help_text='Negativo = descuento, Positivo = entrada')),
                ('stock_resultante', models.PositiveIntegerField(help_text='Stock después del movimiento')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pedido_id', models.IntegerField(blank=True, help_text='ID del pedido que generó el movimiento', null=True)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='products.ingrediente')),
            ],
        ),
    ]
