# Generated by Django 5.2.13 on 2026-04-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_movimientoinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='unidad_medida',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('gramo', 'Gramo'), ('kilogramo', 'Kilogramo'), ('mililitro', 'Mililitro'), ('litro', 'Litro'), ('porcion', 'Porción')], default='unidad', max_length=20),
        ),
    ]
