# Generated by Django 5.2.13 on 2026-04-23 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_ingrediente_unidad_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='disponible',
            field=models.BooleanField(default=True, help_text='¿El producto está activo para ventas?'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='cantidad',
            field=models.IntegerField(help_text='Cantidad de movimiento, negativo para descuento'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='ingrediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ingrediente'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='pedido_id',
            field=models.IntegerField(blank=True, help_text='ID del pedido relacionado si aplica', null=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='stock_resultante',
            field=models.IntegerField(help_text='Stock después del movimiento'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('descuento', 'Descuento'), ('ajuste', 'Ajuste'), ('ingreso', 'Ingreso')], max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='products.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, related_name='productos', to='products.ingrediente'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
