# Generated by Django 5.2.13 on 2026-04-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_ingrediente_unidad_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='disponible',
            field=models.BooleanField(default=True, help_text='¿El producto está activo para ventas?'),
        ),
    ]
